In [20]:
import pandas as pd

In [21]:
data = pd.read_csv("./advent_of_code_day1", header=None)


In [22]:
data.head()

0
0  142156
1  108763
2   77236
3   78186
4  110145

In [61]:
type(data)

pandas.core.frame.DataFrame

In [102]:
r = np.random.rand(10)
r[r < 0.5] = 0
r


array([0.60402161, 0.73988967, 0.        , 0.52310073, 0.        ,
       0.78661423, 0.        , 0.        , 0.6466131 , 0.63462967])

In [108]:
rf = (r > 0)
rf

array([ True,  True, False,  True, False,  True, False, False,  True,
        True])

In [113]:
len(np.where((r > 0)==False)[0])

4

In [98]:
np.random.rand(10) < 0.5

array([False,  True,  True,  True,  True,  True,  True, False, False,
       False])

In [148]:
import numpy as np
def fuelcounter(total, value):
    #print(value.size)
    #print(total.size)
    fuel = np.floor(value/3) - 2
    #print(np.where((fuel > 0)==True)[0])
    fuel[fuel < 0] = 0
    #print(total, value, fuel)
    #print("A", fuel, "<")
    l = len(np.where((fuel > 0)==True)[0])
    #print("full", l)
    #return fuel
#def egal(total, value):
    if l > 0:
        return fuelcounter(total + fuel, fuel)
    else:
        return total

In [149]:
tt = pd.DataFrame(np.array([1969, 100756]))
fuelcountupper = tt.apply(lambda x: fuelcounter(np.zeros(tt.size), x))
fuelcountupper

0
0    966.0
1  50346.0

In [150]:
fuelcountupper = data.apply(lambda x: fuelcounter(np.zeros(data.size), x))
fuelcountupper

0
0   71047.0
1   54349.0
2   38585.0
3   39060.0
4   55040.0
..      ...
95  69442.0
96  44124.0
97  50706.0
98  64830.0
99  46876.0

[100 rows x 1 columns]

In [151]:
np.sum(fuelcountupper)[0] # == 3318632

4975084.0